# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :upload do
    cocoapods
    pgyer(api_key: "ca79d33b069aded70ab9a84fbf803f62", user_key: "6135320e55df2d9d96c642062e22e99b", ipa: "./ipa/KBB_Plus_iOS.ipa", update_description: "update by fastlane")
  end
end
